version: '2'
services:
  db:
    restart: always
    build: db
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    # uncomment the following to enable backup
    #environment:
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1
  app:
    restart: always
    build: app
    links:
      - db:db
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro
  web:
    restart: always
    build: web
    depends_on:
      - db
      - app
    ports:
      - "443:443"
    links:
      - app:app
    volumes:
        # This directory must have cert files
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MATTERMOST_ENABLE_SSL=true
      - PLATFORM_PORT_80_TCP_PORT=80
